Day4
frunzisss/cluj-pre-js-2017 pull request #3
Opened 2017-08-21 15:01 UTC by frunzisss

2017-08-21 17:59 UTC, gcazaciuc requested changes

2017-08-21 17:59 UTC, gcazaciuc commented on css/common.css
> +.footerSkin {
in general in CSS the convention is not camel case but footer-skin('-' as a separator)

2017-08-21 17:59 UTC, gcazaciuc commented on css/common.css
> +.headerSpan {
do not put the tag name in the name of the class. The class can be used on any element

2017-08-21 17:59 UTC, gcazaciuc commented on css/common.css
> +.blue {
do not use color names as the name of classes since when the color changes you need to change all over the place the class name.

2017-08-21 17:59 UTC, gcazaciuc commented on css/login.css
> +    background-color: #1ab2ff;
nice job !

2017-08-21 17:59 UTC, gcazaciuc commented on css/new.css
> +    font-size: 25px !important;
find a way without important

2017-08-21 17:59 UTC, gcazaciuc commented on css/new.css
> +.fieldsetLi {
find a better name

2017-08-21 18:16 UTC, gcazaciuc approved these changes

2017-08-21 20:10 UTC, softvision-alexcarcea approved these changes

2017-08-21 20:10 UTC, softvision-alexcarcea commented on css/evaluations.css
> +.mainTable th,
Just making sure that you indeed want to be targeting only `th` elements inside a `.mainTable` ancestor, but also targeting _all_ `td` elements, regardless of whether or not they have a `.mainTable` ancestor.

2017-08-21 20:10 UTC, softvision-alexcarcea commented on evaluations.html
> +		<header class="header headerSkin">
May I ask what the reason behind these extra `*Skin` classes is?

2017-08-22 06:19 UTC, merged

2017-08-22 11:51 UTC, frunzisss commented on css/common.css
> +.footerSkin {
Solved.

2017-08-22 13:53 UTC, frunzisss commented on css/common.css
> +.headerSpan {
Solved.

2017-08-22 14:12 UTC, frunzisss commented on css/common.css
> +.blue {
Solved.

2017-08-22 14:16 UTC, frunzisss commented on evaluations.html
> +		<header class="header headerSkin">
another class for skin : like a border or something like that

2017-08-22 14:17 UTC, frunzisss commented on css/evaluations.css
> +.mainTable th,
Thx!

2017-08-22 14:18 UTC, frunzisss commented on css/login.css
> +    background-color: #1ab2ff;
Thank you!

2017-08-22 14:21 UTC, frunzisss commented on css/new.css
> +.fieldsetLi {
Solved.